# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cac7d26700f488f87ac9d1f22dce668798610f183a61107dfd8180560ffac4f750aed26c20994d439c42fa45f3ae49f39e7b6d621d74e4bad6fb533f99a302f9

test:
  secret_key_base: b635fa97fcbe780ad3c830072c7445a46dea25e392da0134ef20ea94e37d35dc92a40a7e8a9be262f2fed6069de9bcbc85c71886297cd43bb849332d5f130907

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
